# This file was generated by GoReleaser. DO NOT EDIT.
cask "openai" do
  version "1.18.0"

  on_macos do
    on_intel do
      sha256 "d50ed69d2ac22f71c9cfbb3232cec8baf8e15fc1fcc82b7b2c74be52ca77496c"
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "8554e5a4278e658c6b648e30b27149d199ec1ca597bab459c8a7891cab8d721f"
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "63d4311e1931cd029732a066cd2753ed948a56aef31f8f888db8c7ba515cc222"
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b4cbd825d6975a32d2af2bfd57e62deb73240209cd93bba401abe56bb7e6552"
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openai"
  desc "The official CLI for the OpenAI API."
  homepage "https://developers.openai.com/api/docs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openai"
  manpage "man/man1/openai.1.gz"
  bash_completion "completions/openai.bash"
  fish_completion "completions/openai.fish"
  zsh_completion "completions/openai.zsh"

  # No zap stanza required

end
