# This file was generated by GoReleaser. DO NOT EDIT.
cask "openai" do
  version "1.20.3"

  on_macos do
    on_intel do
      sha256 "6d712315f366fa2a4e56d0fb830397dea60a0c96b276d33f42c39d097962fadf"
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "b2f3301b33c25ec9af4c0fe35f034fb6aa64ac4a849f6904ccc19ac77b3b9c57"
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "b7c281b69b76bdc5502a2c78920b6596cdf0ebda7223b180586f0eb808af2712"
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "72114138aa65dfc3b0bc4b5747c7f0742bd752f879eabe7a387170482ed115f4"
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openai"
  desc "The official CLI for the OpenAI API."
  homepage "https://developers.openai.com/api/docs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openai"
  manpage "man/man1/openai.1.gz"
  bash_completion "completions/openai.bash"
  fish_completion "completions/openai.fish"
  zsh_completion "completions/openai.zsh"

  # No zap stanza required

end
