# This file was generated by GoReleaser. DO NOT EDIT.
cask "openai" do
  version "1.29.3"

  on_macos do
    on_intel do
      sha256 "d3dd99178b784dd517c4a4c1654da4f48b80adddefe3c81e5af5099c21f156e0"
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "fb3676fcd25af609c6b929edf419eafa83e5d82d2965b8be1baa2ba56995a22a"
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "e51bf630ca075ccb7d07adc21726961473d04d65a60f10c91003b862d3c34632"
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a431584fc270418eccfdc0ce8ea4e13308aace2a319fd2c23bbb508ac602f88a"
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openai"
  desc "The official CLI for the OpenAI API."
  homepage "https://developers.openai.com/api/docs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openai"
  manpage "man/man1/openai.1.gz"
  bash_completion "completions/openai.bash"
  fish_completion "completions/openai.fish"
  zsh_completion "completions/openai.zsh"

  # No zap stanza required

end
