# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchard < Formula
  desc "Orchestrator for running Tart Virtual Machines on a cluster of Apple Silicon devices"
  homepage "https://github.com/openai/orchard"
  version "0.56.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openai/orchard/releases/download/0.56.1/orchard-darwin-amd64.tar.gz"
      sha256 "d1bc19e9028483a393b25aab7142aa4387b6c0a206f3813ebe2ae66077629edc"

      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openai/orchard/releases/download/0.56.1/orchard-darwin-arm64.tar.gz"
      sha256 "b0d2f48a03f821072e9b9f36c3fa16e880bdb0d8848868db7c78b33b0a5a7b62"

      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openai/orchard/releases/download/0.56.1/orchard-linux-amd64.tar.gz"
      sha256 "1251f1e71472c6aeee89d646da0e1614c67682b907dd693b4f8ff4f646a1eda4"
      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openai/orchard/releases/download/0.56.1/orchard-linux-arm64.tar.gz"
      sha256 "e3882ed375dcbe78438e488f179b5df07e28f01929398b094efab9d22fe1b98b"
      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
