# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchard < Formula
  desc "Orchestrator for running Tart Virtual Machines on a cluster of Apple Silicon devices"
  homepage "https://github.com/openai/orchard"
  version "0.57.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openai/orchard/releases/download/0.57.0/orchard-darwin-amd64.tar.gz"
      sha256 "b93202610373e1e0f4342ad7e03820e5d74a7891e92cf7532effce2a16b4d256"

      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openai/orchard/releases/download/0.57.0/orchard-darwin-arm64.tar.gz"
      sha256 "63b511cb9ba4ecadda947d70763b4a226f9f0d56422e147cbf2a2b9b2eeabd26"

      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openai/orchard/releases/download/0.57.0/orchard-linux-amd64.tar.gz"
      sha256 "8e54692d5d38eac228b63fc16f0e801c4d7335287b9f1922743e0ac6e4c382d5"
      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openai/orchard/releases/download/0.57.0/orchard-linux-arm64.tar.gz"
      sha256 "5c744e2883ff02b3e3e42b9ecaa42922411843653ea708eb7e37ee393c945d1f"
      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
