# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchard < Formula
  desc "Orchestrator for running Tart Virtual Machines on a cluster of Apple Silicon devices"
  homepage "https://github.com/openai/orchard"
  version "0.56.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openai/orchard/releases/download/0.56.0/orchard-darwin-amd64.tar.gz"
      sha256 "b94cd2013fe4f8f21a31272f9ae61b3d2cae4284659a2e3d9234f164b972c79a"

      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openai/orchard/releases/download/0.56.0/orchard-darwin-arm64.tar.gz"
      sha256 "027bf2d7b2774a59a44b594d5f9e1eae1913e15758e904c8e19675f23be46691"

      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openai/orchard/releases/download/0.56.0/orchard-linux-amd64.tar.gz"
      sha256 "ec68cff6b47d9a1e1013a17d034800f24e5aeec4f487cfe7382150d55ff2b858"
      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openai/orchard/releases/download/0.56.0/orchard-linux-arm64.tar.gz"
      sha256 "960c185826306a0b472f6e3a173ee9cb6662df90b62d8c5ae6a030026b3ddf7b"
      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
