# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Softnet < Formula
  desc "Software networking with isolation for Tart"
  homepage "https://github.com/openai/softnet"
  version "0.22.1"
  depends_on :macos

  url "https://github.com/openai/softnet/releases/download/0.22.1/softnet.tar.gz"
  sha256 "1093be6f77b0c7a75b31cf651ff46844a81d73568184e807494f555280684644"

  define_method(:install) do
    bin.install "softnet"
  end

  on_macos do
    depends_on :macos => :sequoia
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
