# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Softnet < Formula
  desc "Software networking with isolation for Tart"
  homepage "https://github.com/openai/softnet"
  version "0.20.1"
  depends_on :macos

  url "https://github.com/openai/softnet/releases/download/0.20.1/softnet.tar.gz"
  sha256 "4a94100aac9bc83b5527af923217ab615321a5322425484c4342947a6ae00214"

  define_method(:install) do
    bin.install "softnet"
  end

  on_macos do
    depends_on :macos => :sequoia
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
