# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Softnet < Formula
  desc "Software networking with isolation for Tart"
  homepage "https://github.com/openai/softnet"
  version "0.20.0"
  depends_on :macos

  url "https://github.com/openai/softnet/releases/download/0.20.0/softnet.tar.gz"
  sha256 "46f6d5056aaa3d445f56040283d60d9b91980634cb525d8bb6b687a83b62575c"

  define_method(:install) do
    bin.install "softnet"
  end

  on_macos do
    depends_on :macos => :sequoia
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
