# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TartGuestAgent < Formula
  desc "Guest agent for Tart VMs"
  homepage "https://github.com/openai/tart-guest-agent"
  version "0.13.0"
  license "FSL-1.1-Apache-2.0"

  on_macos do
    url "https://github.com/openai/tart-guest-agent/releases/download/v0.13.0/tart-guest-agent-darwin-all.tar.gz"
    sha256 "ee0ef7bd44c19dbf65d3767f540a57f5e83034ecab52ddf7108898e45f15f2c2"

    define_method(:install) do
      bin.install "tart-guest-agent"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openai/tart-guest-agent/releases/download/v0.13.0/tart-guest-agent-linux-amd64.tar.gz"
      sha256 "ab279befb0b03d963b4b1bcdf416d581a6c71cc218f9bab3541c4fdddf8c2df1"
      define_method(:install) do
        bin.install "tart-guest-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openai/tart-guest-agent/releases/download/v0.13.0/tart-guest-agent-linux-arm64.tar.gz"
      sha256 "0829ceb3f29d828749f0aa6133b54eeefbc3aecfbf1de5adff7f128f3ec30309"
      define_method(:install) do
        bin.install "tart-guest-agent"
      end
    end
  end
end
