# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tart < Formula
  desc "Run macOS and Linux VMs on Apple Hardware"
  homepage "https://github.com/openai/tart"
  version "2.36.0"
  license "FSL-1.1-ALv2"

  depends_on "openai/tools/softnet"
  depends_on :macos

  url "https://github.com/openai/tart/releases/download/2.36.0/tart.tar.gz"
  sha256 "c72a8ab8d78a6498a1e42688b1a1ec6c512ce46ca35a3a3be130c3de1440c7e8"

  define_method(:install) do
    libexec.install Dir["*"]
    bin.write_exec_script "#{libexec}/tart.app/Contents/MacOS/tart"
  end

  on_macos do
    depends_on :macos => :ventura
  end
  def post_install
    generate_completions_from_executable(libexec/"tart.app/Contents/MacOS/tart", "--generate-completion-script")
  end

  def caveats
    <<~EOS
      Tart has been installed. You might want to reduce the default DHCP lease time
      from 86,400 to 600 seconds to avoid DHCP shortage when running lots of VMs daily:

        sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.InternetSharing.default.plist bootpd -dict DHCPLeaseTimeSecs -int 600

      See https://tart.run/faq/#changing-the-default-dhcp-lease-time for more details.
    EOS
  end
end
