# typed: strict
# frozen_string_literal: true

# Generated by tunnel-client release automation. DO NOT EDIT.
class TunnelClient < Formula
  desc "Customer-run agent for Secure MCP Tunnel"
  homepage "https://github.com/openai/tunnel-client"
  version "0.0.13"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://persistent.oaistatic.com/tunnel-client/v#{version}/tunnel-client-v#{version}-darwin-amd64.zip"
      sha256 "c683e15d84fb997f5af1cc7c4cb55008e19a555a9ed2ec0f89a5ff426d85f85c"
    end
    on_arm do
      url "https://persistent.oaistatic.com/tunnel-client/v#{version}/tunnel-client-v#{version}-darwin-arm64.zip"
      sha256 "15abf165f06050af642c948ba6bd6c905191dc5420a9422dadde2b49d892e2c6"
    end
  end

  on_linux do
    on_intel do
      url "https://persistent.oaistatic.com/tunnel-client/v#{version}/tunnel-client-v#{version}-linux-amd64.zip"
      sha256 "e71f37b424126513173d5e3590687c0b5ccf6e8ef3fba900104d1f8c60dad906"
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://persistent.oaistatic.com/tunnel-client/v#{version}/tunnel-client-v#{version}-linux-arm64.zip"
        sha256 "9d214a805bec213a3a156dc2a4460a6dfe2f35b0c00ba20609d002bf5e6469f8"
      end
    end
  end

  def install
    libexec.install "tunnel-client", "cloudflared", "cloudflared-manifest.json"
    bin.write_exec_script libexec/"tunnel-client"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tunnel-client --version")
  end
end
