# frozen_string_literal: true

require "uri"

def validate(name, checks)
  failed = checks.reject { |_description, passed| passed }.keys
  abort("#{name} validation failed: #{failed.join(', ')}") unless failed.empty?
end

cask = File.read("Casks/openai.rb")
cask_checks = {
  "generated header" => cask.start_with?("# This file was generated by GoReleaser. DO NOT EDIT.\n"),
  "openai cask token" => cask.match?(/^cask "openai" do$/),
  "semantic version" => cask.match?(/^  version "\d+\.\d+\.\d+"$/),
  "homepage" => cask.include?('  homepage "https://developers.openai.com/api/docs"'),
  "binary" => cask.include?('  binary "openai"'),
  "manpage" => cask.include?('  manpage "man/man1/openai.1.gz"'),
  "macos amd64 zip" => cask.match?(/openai_#\{version\}_macos_amd64\.zip/),
  "macos arm64 zip" => cask.match?(/openai_#\{version\}_macos_arm64\.zip/),
  "linux amd64 tarball" => cask.match?(/openai_#\{version\}_linux_amd64\.tar\.gz/),
  "linux arm64 tarball" => cask.match?(/openai_#\{version\}_linux_arm64\.tar\.gz/),
  "release host" => cask.scan(%r{https://github\.com/openai/openai-cli/releases/download/v#\{version\}/}).length == 4,
  "sha256 count" => cask.scan(/^\s+sha256 "[a-f0-9]{64}"$/).length == 4,
}
validate("Casks/openai.rb", cask_checks)

formulas = {
  "Formula/orchard.rb" => {
    class_name: "Orchard",
    repository: "orchard",
    install: 'bin.install "orchard"',
  },
  "Formula/softnet.rb" => {
    class_name: "Softnet",
    repository: "softnet",
    install: 'bin.install "softnet"',
  },
  "Formula/tart-guest-agent.rb" => {
    class_name: "TartGuestAgent",
    repository: "tart-guest-agent",
    install: 'bin.install "tart-guest-agent"',
  },
  "Formula/tart.rb" => {
    class_name: "Tart",
    repository: "tart",
    install: 'bin.write_exec_script "#{libexec}/tart.app/Contents/MacOS/tart"',
    dependency: 'depends_on "openai/tools/softnet"',
  },
}

unknown_formulas = Dir["Formula/*.rb"] - formulas.keys
abort("Unexpected formula: #{unknown_formulas.join(', ')}") unless unknown_formulas.empty?

formulas.each do |path, expected|
  next unless File.exist?(path)

  formula = File.read(path)
  version = formula[/^\s*version "(\d+\.\d+\.\d+)"$/, 1]
  urls = formula.scan(/^\s*url "([^"]+)"$/).flatten
  shas = formula.scan(/^\s*sha256 "([a-f0-9]+)"$/).flatten
  release_url = if version
    %r{\Ahttps://github\.com/openai/#{Regexp.escape(expected[:repository])}/releases/download/v?#{Regexp.escape(version)}/[^/]+\z}
  end
  artifact_name = %r{/#{Regexp.escape(expected[:repository])}(?:[-_.][^/]+)?\z}

  checks = {
    "generated header" => formula.include?("# This file was generated by GoReleaser. DO NOT EDIT.\n"),
    "formula class" => formula.match?(/^class #{expected[:class_name]} < Formula$/),
    "semantic version" => !version.nil?,
    "homepage" => formula.include?(%Q(homepage "https://github.com/openai/#{expected[:repository]}")),
    "release URLs" => !urls.empty? && release_url && urls.all? { |url| url.match?(release_url) },
    "artifact names" => !urls.empty? && urls.all? { |url| URI.decode_www_form_component(url).match?(artifact_name) },
    "sha256 values" => shas.length == urls.length && shas.all? { |sha| sha.match?(/\A[a-f0-9]{64}\z/) },
    "binary install" => formula.include?(expected[:install]),
    "tap dependency" => !expected[:dependency] || formula.include?(expected[:dependency]),
  }
  validate(path, checks)
end
